### ISSUE TITLE
visualization code for spotting results

### ISSUE THREAD

**Issue by chentianyangWHU** [ViTAE-Transformer/DeepSolo#11]
Could you please release code of the visualization code of spotting results as you showed in Figure 4 and Figure 11? Thank you

**Comment by ymy-k** [comment]
Figure 4: You can return and save the sampling_locations & attention_weights in adet/layers/ms_deform_attn.py, then plot them on the image.
Figure 11: Do you mean the points on center curve? You can find the code [here](https://github.com/ViTAE-Transformer/DeepSolo/blob/0957f7f5c231eff6e207171cee33a42177d4b9c9/adet/utils/visualizer.py#L95-L97)

**Comment by chentianyangWHU** [comment]
> Figure 4: You can return and save the sampling_locations & attention_weights in adet/layers/ms_deform_attn.py, then plot them on the image. Figure 11: Do you mean the points on center curve? You can find the code [here](https://github.com/ViTAE-Transformer/DeepSolo/blob/0957f7f5c231eff6e207171cee33a42177d4b9c9/adet/utils/visualizer.py#L95-L97)

thanks a lot, I got it.
