### ISSUE TITLE
Loading the dataset seems to be slower

### ISSUE THREAD

**Issue by yyyyyxie** [ViTAE-Transformer/DeepSolo#14]
I'm facing an issue with a significant delay when loading my dataset, and I'm unsure about the underlying cause. I would greatly appreciate any insights or suggestions you can provide.

<img width="862" alt="image" src="https://github.com/ViTAE-Transformer/DeepSolo/assets/101948858/3e64133c-2209-498e-b105-4258db8855f3">

**Comment by ymy-k** [comment]
I can't get the problem from the screenshot. It actually takes some seconds to load datasets such as synthtext.
