### ISSUE TITLE
IC13 finetune Config

### ISSUE THREAD

**Issue by linxid** [ViTAE-Transformer/DeepSolo#15]
Can you provide IC13 finetune config file, thx

**Comment by linxid** [comment]
"ic13_train" and "ic13_test" is "ic13/train_96voc.json" and  "ic13/train_37voc.json" in builtin.py:_PREDEFINED_SPLITS_TEXT ?

**Comment by ymy-k** [comment]
Use "ic13/train_37voc.json". "ic13_test" is not uploaded

**Comment by linxid** [comment]
Can you upload ic13 test data, we need to evulate model on this dataset. Thx
