### ISSUE TITLE
How can I fine-tune the DeepSolo model and trained it in different language?

### ISSUE THREAD

**Issue by Gorgerbin** [ViTAE-Transformer/DeepSolo#17]

**Comment by Gorgerbin** [comment]
@ymy-k Thanks a lot. Now I know I can refer to the ABCNet model using "chn_cls_list.txt", but I'm confused if I can use the pretrained ViTAEv2-S model. It seems not good because the voc_size doesn't match.

**Comment by ymy-k** [comment]
It's pretrained on English data. Thus, it's not a good choice to use it.

**Comment by Gorgerbin** [comment]
@ymy-k So kind of you. BTW, when will the Chinese model be available?

**Comment by ymy-k** [comment]
Maybe this week, I will update the Chinese model first.

**Comment by Gorgerbin** [comment]
Thank you and hope to release sooner.

**Comment by Gorgerbin** [comment]
Thank you so much!!
