### ISSUE TITLE
Do we need a lexicon file to finetune your pretrained model?

### ISSUE THREAD

**Issue by phuumm** [ViTAE-Transformer/DeepSolo#24]
thanks in advance!

**Comment by ymy-k** [comment]
Do you mean the word lexicon? It's not required.

**Comment by phuumm** [comment]
Sorry, if I'm using another language dataset, it's still not necessary, right?

**Comment by ymy-k** [comment]
Yes. If it's not available, you can ignore it. You can also refer to issue #17 for preparing another language dataset. Since the existing character classes in provided models may not fit your language, it's recomended to pre-train and fine-tune a new model with target language data.

**Comment by phuumm** [comment]
thank you !
