### ISSUE TITLE
setup.py build develop generates a lot of warnings

### ISSUE THREAD

**Issue by bit-scientist** [ViTAE-Transformer/DeepSolo#28]
First off, thank you for the good work.

I'm following the installation part and the last command `python setup.py build develop` generated a lot of warnings. After inspection, I didn't find them to be significant, but decided to ask anyway. The whole log file resides >> [sh.log](https://github.com/ViTAE-Transformer/DeepSolo/files/11931826/sh.log). May I proceed with my exploration further? Thanks.

OS: Linux 20.04.

**Comment by ymy-k** [comment]
It seems that the codebase was successfully built. Don't mind the warning.

**Comment by bit-scientist** [comment]
Appreciate it, closing the issue
