### ISSUE TITLE
Chinese text recognition scene

### ISSUE THREAD

**Issue by milely** [ViTAE-Transformer/DeepSolo#3]
Hello~. Thanks for your good job. I want to ask
whether the framework of  deepsolo suitable for Chinese text recognition.Compared to the english in natural scene, Chinese text recognition scene has the characteristics of more number of categories and longer text lines.Moreover, The visual features of Chinese characters are more complex than Latin characters. I would like to know if you have tried Chinese character scenes, if I want to use Deepsolo for Chinese character scenes, do you have any suggestions?

**Comment by ymy-k** [comment]
Hi, it's a good question. Chinese spotting and multi-language spotting are in my plan. I'm working on this.

**Comment by ymy-k** [comment]
Good news. Thanks.

**Comment by ymy-k** [comment]
Hi, I evaluate DeepSolo on ReCTS recently. It achieves 78.3% 1-NED (voc_size: 5462, batch size 8, pretrained on SynthChinese130K+LSVT+ArT+ReCTS for 400K iterations, the same as SwinTS, ABCNet-v2, ABINet++...), being 1.8% better than previous SOTA ABINet++ with far less training iterations. The result was made public on the [official leadboard](https://rrc.cvc.uab.es/?ch=12&com=evaluation&task=4).

**Comment by ymy-k** [comment]
Hi, I evaluate DeepSolo on ReCTS recently. It achieves 78.3% 1-NED (voc_size: 5462, batch size 8, pretrained on SynthChinese130K+LSVT+ArT+ReCTS for 400K iterations, the same datasets as SwinTS, ABCNet-v2, ABINet++...), being 1.8% better than previous SOTA ABINet++ with far less training iterations. The result was made public on the [official leadboard](https://rrc.cvc.uab.es/?ch=12&com=evaluation&task=4).

**Comment by Gorgerbin** [comment]
can you release the model trained on chinese dataset please?

**Comment by ymy-k** [comment]
Yes, it will be released in next few weeks.
