### ISSUE TITLE
Issue with Evaluation Metrics and Missing CSV File for Total-Test Dataset

### ISSUE THREAD

**Issue by AdemBoukhris457** [ViTAE-Transformer/DeepSolo#34]
I am encountering an issue with the chosen model's evaluation on the Total-Test dataset. When I attempted to evaluate the model using 300 testing images, the prediction results were saved in a JSON file called "text_results.json." However, upon inspection of the evaluation metrics (precision, recall, hmean), I noticed that all of them are set to 0, indicating that the evaluation process did not produce valid results.

Furthermore, I am unable to locate the CSV file that should contain the evaluation information.
![evaluation results](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/801d46e9-4fb2-43c3-8e83-15440ccaec25)
![Chosen Model](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/5996bb3d-6ab2-4929-9c4a-5043174e9aab)

**Comment by ymy-k** [comment]
Did you prepare the [Evaluation ground-truth] and organize them as mentioned in README?

**Comment by AdemBoukhris457** [comment]
yes i organized them as mentioned in README.
![datasets](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/122a0925-b638-4c70-af27-5c5f880f0bc4)
.

**Comment by AdemBoukhris457** [comment]
I'm using your data, your ground-truth data, and the result is not coming out.
The fourth green line is reporting: 0.0000,0.0000,0.0000.
How can i check that the metrics are being computed ?
![evaluation results_2](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/ab34d8ba-4a7a-47be-aa37-cc2d157b5ab0)

**Comment by ymy-k** [comment]
Did you change any codes?

**Comment by AdemBoukhris457** [comment]
I just changed the batch size from the length of the input to 4.

**Comment by AdemBoukhris457** [comment]
the changement was done in detectron2 file

**Comment by ymy-k** [comment]
![1691145051(1)](https://github.com/ViTAE-Transformer/DeepSolo/assets/72698155/f3b0a0b1-08e4-4f9f-80eb-9ac379172999)
I just evaluated the selected model on a 2080Ti GPU following my README and could not reproduce your issue.

**Comment by ymy-k** [comment]
Maybe because of the operating system?

**Comment by kangmengning** [comment]
> I am encountering an issue with the chosen model's evaluation on the Total-Test dataset. When I attempted to evaluate the model using 300 testing images, the prediction results were saved in a JSON file called "text_results.json." However, upon inspection of the evaluation metrics (precision, recall, hmean), I noticed that all of them are set to 0, indicating that the evaluation process did not produce valid results.
> 
> Furthermore, I am unable to locate the CSV file that should contain the evaluation information. ![evaluation results](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/801d46e9-4fb2-43c3-8e83-15440ccaec25) ![Chosen Model](https://github.com/ViTAE-Transformer/DeepSolo/assets/61518107/5996bb3d-6ab2-4929-9c4a-5043174e9aab)

I also encountered the same problem. Could you please tell me how you solved it at that time?
