### ISSUE TITLE
Datasets conversion tool

### ISSUE THREAD

**Issue by linxid** [ViTAE-Transformer/DeepSolo#4]
This is a great job, Can you provide dataset conversion script, thanks.

**Comment by ymy-k** [comment]
Overall, 8 bezier control points for each text instance are required, you can refer to the [link](https://drive.google.com/open?id=1bFmdXCCsW0bj0qFgQl1MJarlWkwPSv_U) in [ABCNet](https://github.com/Yuliang-Liu/bezier_curve_text_spotting) to generate Bezier-curve. Note that, please make sure the bbox is correct (there is a issue when processing the bbox in the provided code).
The conversion for sampling points already lies in [here](https://github.com/ViTAE-Transformer/DeepSolo/blob/bfd36a1a7248223d4bfea0753cbcd5fc38ccad76/adet/data/datasets/text.py#L191-L202).

**Comment by linxid** [comment]
I have an irregularly shaped marker that starts at the top of the text box instead of the top left corner. How can I generate Bezier-curve in this case.

**Comment by ymy-k** [comment]
If the text is not highly curved, it doesn't matter to sample points on the axis-aligned bbox as boundary gt. Otherwise, it seems the shape of text cannot be accurately represented.

**Comment by RazinAleksandr** [comment]
Can you provide app which you used for data markup, thanks?
