### ISSUE TITLE
weak_voc_new.txt问题

### ISSUE THREAD

**Issue by jihuan1203** [ViTAE-Transformer/DeepSolo#47]
我在运行train.net.py时，报错FileNotFoundError: [Errno 2] No such file or directory: 'datasets/totaltext/weak_voc_new.txt'，'datasets/totaltext/weak_voc_new.txt'文件是只得什么，我在readme.md的数据集组成并没有看到关于这里的介绍

**Comment by ymy-k** [comment]
下载数据的时候有这些文件
