### ISSUE TITLE
KeyError: 'e2e_method'

### ISSUE THREAD

**Issue by jihuan1203** [ViTAE-Transformer/DeepSolo#59]
python tools/train_net.py --config-file configs/R_50/IC15**/finetune_150k_tt_mlt_13_15.yaml** --eval-only MODEL.WEIGHTS model/**ic15_res50_finetune_synth-tt-mlt-13-15.pth**  报错：Traceback (most recent call last):
  File "tools/train_net.py", line 309, in <module>
    launch(
  File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "tools/train_net.py", line 286, in main
    res = Trainer.test(cfg, model) # d2 defaults.py
  File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 608, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset
    results = evaluator.evaluate()
  File "/media/wit/HDD_1/lj/DeepSolo-main/adet/evaluation/text_evaluation_all.py", line 435, in evaluate
    text_result["e2e_method"] = "None-" + text_result["e2e_method"] 
**KeyError: 'e2e_method'**

**Comment by zfx1730792150** [comment]
请问您解决了吗

**Comment by zfx1730792150** [comment]
> python tools/train_net.py --config-file configs/R_50/IC15**/finetune_150k_tt_mlt_13_15.yaml** --eval-only MODEL.WEIGHTS model/**ic15_res50_finetune_synth-tt-mlt-13-15.pth** 报错：Traceback (most recent call last): File "tools/train_net.py", line 309, in launch( File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch main_func(*args) File "tools/train_net.py", line 286, in main res = Trainer.test(cfg, model) # d2 defaults.py File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 608, in test results_i = inference_on_dataset(model, data_loader, evaluator) File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset results = evaluator.evaluate() File "/media/wit/HDD_1/lj/DeepSolo-main/adet/evaluation/text_evaluation_all.py", line 435, in evaluate text_result["e2e_method"] = "None-" + text_result["e2e_method"] **KeyError: 'e2e_method'**
请问您解决了吗

**Comment by jihuan1203** [comment]
没有，并且这个错误时隐时现



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 9, 2024 22:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ViTAE-Transformer/DeepSolo] KeyError: 'e2e_method' (Issue #59)




  
python tools/train_net.py --config-file configs/R_50/IC15**/finetune_150k_tt_mlt_13_15.yaml** --eval-only MODEL.WEIGHTS model/ic15_res50_finetune_synth-tt-mlt-13-15.pth 报错：Traceback (most recent call last): File "tools/train_net.py", line 309, in launch( File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch main_func(*args) File "tools/train_net.py", line 286, in main res = Trainer.test(cfg, model) # d2 defaults.py File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 608, in test results_i = inference_on_dataset(model, data_loader, evaluator) File "/home/wit/anaconda3/envs/lj_py3.8pt1.10/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 204, in inference_on_dataset results = evaluator.evaluate() File "/media/wit/HDD_1/lj/DeepSolo-main/adet/evaluation/text_evaluation_all.py", line 435, in evaluate text_result["e2e_method"] = "None-" + text_result["e2e_method"] KeyError: 'e2e_method'
 请问您解决了吗

**Comment by YuMianJie** [comment]
It is necessary to check the path of the evaluation file or the result file, which causes a failure to load the ZIP file. You can output the file path and compare it with the actual path.

**Comment by zfx1730792150** [comment]
> It is necessary to check the path of the evaluation file or the result file, which causes a failure to load the ZIP file. You can output the file path and compare it with the actual path.

谢谢！
