### ISSUE TITLE
what do the `rec` values in annotation .json files mean?

### ISSUE THREAD

**Issue by mazharsaif** [ViTAE-Transformer/DeepSolo#8]

**Comment by ymy-k** [comment]
the index of character

**Comment by ymy-k** [comment]
the index of character for recognition

**Comment by HqiTao** [comment]
Hi, @ymy-k 

Since the rec value represents the recognized character index, I guess the numbers 37 and 96 in the file names train_37voc.json and train_96voc.json represent the character list's capacity.

 If that's the case, could you please tell me how to find these two character lists?
